/* ================= TOPIC DATABASE =================
   st:'done' = chapter file exists and is linked.
   st:'wait' = placeholder shown; file name already reserved in "f".
   To add a finished chapter: set its st to 'done'. Nothing else.
==================================================== */
var TOPICS=[
{id:'quantities',n:'1',lvl:'AS',ic:'📐',t:'Physical Quantities & Units',st:'done',f:'topic-01-physical-quantities.html',pts:['The seven base quantities and SI base units (kg, m, s, K, A, mol)','Prefixes p → T; scientific notation and orders of magnitude','Homogeneity of equations — dimensional checking','Estimation of physical quantities to the nearest order of magnitude','Systematic vs random errors; accuracy vs precision; uncertainty']},
{id:'kinematics',n:'2',lvl:'AS',ic:'🏃',t:'Kinematics & Accelerated Motion',st:'done',f:'topic-02-kinematics.html',pts:['Distance, displacement, speed, velocity, acceleration','Motion graphs: gradients and areas','Suvat equations with full derivations','Free fall and the measurement of g','Projectile motion']},
{id:'dynamics',n:'3',lvl:'AS',ic:'🚀',t:'Dynamics',st:'done',f:'topic-03-dynamics.html',pts:["Newton's three laws of motion; F = ma and F = Δp/Δt",'Mass, weight W = mg, and free-body diagrams','Equilibrium of coplanar forces; triangle of forces','Linear momentum and its conservation','Drag, upthrust, and terminal velocity (qualitative)']},
{id:'forces',n:'4',lvl:'AS',ic:'⚖️',t:'Forces, Density & Pressure',st:'done',f:'topic-04-forces-density-pressure.html',pts:['Moment of a force = F × d; couples and torque','Centre of gravity; conditions for equilibrium','Density ρ = m/V and pressure p = F/A','Pressure in fluids: Δp = ρgΔh','Upthrust and Archimedes’ principle']},
{id:'energy',n:'5',lvl:'AS',ic:'⚡',t:'Work, Energy & Power',st:'done',f:'topic-05-work-energy-power.html',pts:['Work done W = Fs cos θ; efficiency','Kinetic energy ½mv² and gravitational PE mgΔh','Conservation of energy and energy transformations','Power P = W/t = Fv','Deriving ½mv² from the suvat equations']},
{id:'momentum',n:'6',lvl:'AS',ic:'🎱',t:'Momentum',st:'done',f:'topic-06-momentum.html',pts:['Linear momentum p = mv; impulse Ft = Δp','Force–time graphs and area = change in momentum','Conservation of momentum in one dimension','Elastic vs inelastic collisions','Two-dimensional collision sketches (vector triangle)']},
{id:'materials',n:'7',lvl:'AS',ic:'🧱',t:'Matter & Materials',st:'done',f:'topic-07-matter-materials.html',pts:['Microscopic structure of solids, liquids and gases','Hooke’s law F = kx; elastic limit; energy in a spring ½Fx','Stress, strain and Young modulus E = stress/strain','Stress–strain graphs: brittle, ductile, polymeric behaviour','Experiment: Young modulus of a wire']},
{id:'waves',n:'8',lvl:'AS',ic:'🌊',t:'Waves',st:'done',f:'topic-08-waves.html',pts:['Transverse vs longitudinal waves; polarisation','Amplitude, wavelength, frequency, period; v = fλ','The electromagnetic spectrum and intensity ∝ amplitude²','Phase and phase difference (radians and degrees)','Doppler effect for sound and light (qualitative + formula)']},
{id:'superposition',n:'9',lvl:'AS',ic:'🎼',t:'Superposition & Stationary Waves',st:'done',f:'topic-09-superposition.html',pts:['Principle of superposition; coherence','Interference and path difference (nλ, (n+½)λ)','Young’s double slit: Δx = λD/a; diffraction grating d sinθ = nλ','Stationary waves: nodes, antinodes, harmonics on strings and in pipes','Resonance and applications']},
{id:'electricity',n:'10',lvl:'AS',ic:'🔌',t:'Electricity: Current, p.d. & Resistance',st:'done',f:'topic-10-electricity.html',pts:['Charge Q = It; current as rate of flow of charge','Potential difference V = W/Q; the electron-volt','Resistance R = V/I; Ohm’s law','I–V characteristics: ohmic, filament lamp, diode','Resistivity ρ = RA/L; thermistors and LDRs']},
{id:'circuits',n:'11',lvl:'AS',ic:'🔋',t:'D.C. Circuits',st:'done',f:'topic-11-dc-circuits.html',pts:["Kirchhoff's first and second laws",'Series and parallel resistance; potential dividers','Cells, e.m.f. and internal resistance: E = I(R + r)','Output voltage of sensing circuits with thermistors/LDRs','Practical circuit calculations and voltmeter effects']},
{id:'atomic',n:'12',lvl:'AS',ic:'⚛️',t:'Atomic Structure & Particle Physics',st:'done',f:'topic-12-atomic-particles.html',pts:['The nuclear atom; Rutherford α-scattering experiment','Proton number, nucleon number, isotopes','Quark structure of protons, neutrons and mesons (u, d, s)','Beta decay and the neutrino; antimatter','Fundamental particles and simple Feynman diagrams']},
{id:'circular',n:'13',lvl:'A2',ic:'🎡',t:'Motion in a Circle',st:'done',f:'topic-13-circular-motion.html',pts:['Radian measure; angular displacement and ω = 2π/T','v = rω; centripetal acceleration v²/r = rω²','Centripetal force F = mv²/r','Applications: cars on bends, banked tracks, vertical circles','Worked past-paper circular motion problems']},
{id:'gravity',n:'14',lvl:'A2',ic:'🌍',t:'Gravitational Fields',st:'done',f:'topic-14-gravitational-fields.html',pts:["Gravitational field strength g; field lines","Newton's law of gravitation F = GMm/r²",'g = GM/r² and g = GM/R² at a surface','Gravitational potential φ = −GM/r; potential gradient','Satellites: orbital speed, geostationary and polar orbits']},
{id:'thermal',n:'15',lvl:'A2',ic:'🌡️',t:'Thermal Physics & Temperature',st:'done',f:'topic-15-thermal-physics.html',pts:['Thermal equilibrium; Celsius and Kelvin scales','Thermometers: thermistor, thermocouple, resistance','Specific heat capacity c and specific latent heat L','Molecular view of the three states of matter','Calorimetry calculations and experiments']},
{id:'gases',n:'16',lvl:'A2',ic:'🎈',t:'Ideal Gases',st:'done',f:'topic-16-ideal-gases.html',pts:['The mole and Avogadro constant; pV = nRT = NkT','Kinetic theory assumptions and pV = ⅓ Nmc²','Mean translational kinetic energy = (3/2)kT','r.m.s. speed; Boltzmann constant','Behaviour of real vs ideal gases']},
{id:'thermo',n:'17',lvl:'A2',ic:'♨️',t:'Thermodynamics',st:'done',f:'topic-17-thermodynamics.html',pts:['Internal energy U; heating and doing work','First law: ΔU = q + W','Work done by a gas W = pΔV (constant pressure)','Isothermal and adiabatic processes on p–V diagrams','Energy changes along thermodynamic cycles']},
{id:'oscillations',n:'18',lvl:'A2',ic:'🕰️',t:'Oscillations',st:'done',f:'topic-18-oscillations.html',pts:['Simple harmonic motion: a = −ω²x','x = x₀ sin ωt; v–x and energy interchange','Period of mass–spring and simple pendulum systems','Damping: light, heavy, critical; forced oscillations','Resonance: benefits and hazards']},
{id:'efields',n:'19',lvl:'A2',ic:'🧲',t:'Electric Fields & Coulomb’s Law',st:'done',f:'topic-19-electric-fields.html',pts:["Electric field strength E = F/Q = −ΔV/Δs","Coulomb's law F = Qq/(4πε₀r²)","Point-charge field E = Q/(4πε₀r²)","Electric potential V = Q/(4πε₀r)","Field line and equipotential sketches; electron deflection"]},
{id:'capacitance',n:'20',lvl:'A2',ic:'🗄️',t:'Capacitance',st:'done',f:'topic-20-capacitance.html',pts:['Capacitance C = Q/V; the farad','Series and parallel capacitor combinations','Energy stored: ½QV = ½CV²','Discharge: time constant τ = RC, exponential graphs','Charging/discharging calculations with ln']},
{id:'magnetics',n:'21',lvl:'A2',ic:'🧭',t:'Magnetic Fields & Electromagnetism',st:'done',f:'topic-21-magnetic-fields.html',pts:['Magnetic flux density B; F = BIL sin θ and F = BQv sin θ','Force between parallel current-carrying conductors','Magnetic flux Φ = BA and flux linkage NΦ','The Hall effect and Hall voltage','D.C. motors and moving-coil meters']},
{id:'particles',n:'22',lvl:'A2',ic:'🌀',t:'Motion of Charged Particles',st:'done',f:'topic-22-charged-particles.html',pts:['Circular orbits in magnetic fields: qvB = mv²/r','Radius r = mv/Bq; velocity selectors','The mass spectrometer principle','Helical motion and combined E and B fields','Worked particle-physics trajectory problems']},
{id:'induction',n:'23',lvl:'A2',ic:'🔁',t:'Electromagnetic Induction',st:'done',f:'topic-23-electromagnetic-induction.html',pts:["Faraday's law: emf = rate of change of flux linkage","Lenz's law and its link to energy conservation",'Generators, dynamos, and the a.c. waveform','Transformers: Vs/Vp = Ns/Np and efficiency','Eddy currents: uses and losses']},
{id:'ac',n:'24',lvl:'A2',ic:'〰️',t:'Alternating Currents',st:'done',f:'topic-24-alternating-currents.html',pts:['Sinusoidal a.c.: peak, r.m.s. values; I_rms = I₀/√2','Mean power in resistive loads','Rectification: half-wave and full-wave bridges','Smoothing capacitors; ripple and their effects','Oscilloscope measurements on a.c. signals']},
{id:'quantum',n:'25',lvl:'A2',ic:'💡',t:'Quantum Physics',st:'done',f:'topic-25-quantum-physics.html',pts:['Photons and E = hf; the photoelectric effect','hf = Φ + ½mv²_max; work function and threshold frequency','Electron diffraction and wave-particle duality','de Broglie wavelength λ = h/p','Line spectra, energy levels, and excitation']},
{id:'nuclear',n:'26',lvl:'A2',ic:'☢️',t:'Nuclear Physics',st:'done',f:'topic-26-nuclear-physics.html',pts:['Nuclide notation; α, β⁻, β⁺ and γ emissions','Mass defect and binding energy: E = mc²','Binding energy per nucleon; fission and fusion','Activity A = λN; decay law N = N₀e^(−λt)','Half-life and carbon dating']},
{id:'medical',n:'27',lvl:'A2',ic:'🩻',t:'Medical Physics & Imaging',st:'done',f:'topic-27-medical-physics.html',pts:['Production and spectrum of X-rays','Attenuation: I = I₀e^(−μx); contrast media','CT scanning; ultrasound and acoustic impedance Z = ρc','Reflection coefficient; A-scan and B-scan','PET scanning and MRI principles (Larmor precession)']},
{id:'cosmos',n:'28',lvl:'A2',ic:'🌌',t:'Astronomy & Cosmology',st:'done',f:'topic-28-astronomy-cosmology.html',pts:['Stellar sizes; luminosity and the inverse-square law','Standard candles and the distance ladder','Redshift z = Δλ/λ and recessional velocity','Hubble law v = H₀d; the age of the universe','The Big Bang, CMBR, and dark matter (qualitative)']},
{id:'practical',n:'P1',lvl:'RES',ic:'🧪',t:'Practical Work & Experimental Skills',st:'done',f:'topic-P1-practical-skills.html',pts:['Planning, variables, and risk assessment','Uncertainties: absolute, fractional, percentage; propagation','Graphs: gradients, intercepts, worst acceptable lines','Evaluation: limitations and improvements','Key experiments: g, Young modulus, resistivity, double slit, internal resistance']},
{id:'formulae',n:'P2',lvl:'RES',ic:'📋',t:'List of Formulae & Data',st:'done',f:'topic-P2-formulae-data.html',pts:['Master formula sheet by topic (auto-compiled as topics are completed)','Physical constants table (below)','Unit conversions and trigonometric identities','Exam-technique notes on data handling']},
{id:'glossary',n:'P3',lvl:'RES',ic:'📖',t:'Glossary & Index',st:'done',f:'topic-P3-glossary-index.html',pts:['Command words used by Cambridge (define, describe, explain, show that…)','Alphabetical glossary of core terms (below)','Quick index of experiments and graphs']}
];

var GLY=[['Displacement','Distance moved in a specified direction (vector).'],['Velocity','Rate of change of displacement (vector).'],['Acceleration','Rate of change of velocity (vector).'],['Moment','Turning effect of a force = force × perpendicular distance from pivot.'],['Couple','Pair of equal, opposite, parallel forces producing rotation; torque = F × separation.'],['Work done','Energy transferred by a force: W = Fs cos θ.'],['Power','Rate of doing work: P = W/t = Fv.'],['Stress','Force per unit area: σ = F/A.'],['Strain','Extension per unit original length: ε = x/L.'],['Young modulus','Stress ÷ strain; a measure of stiffness.'],['Coherence','Constant phase relationship between two waves.'],['e.m.f.','Energy converted per unit charge by a source: E = W/Q.'],['Internal resistance','Resistance within a cell opposing current flow.'],['Time constant','RC; the time for a capacitor discharge to fall to 37%.'],['Binding energy','Minimum energy needed to separate a nucleus into its nucleons.'],['Half-life','Time for activity (or number of nuclei) to halve.']];

var CONST=[['Acceleration of free fall, g','9.81 m s⁻²'],['Speed of light in vacuum, c','3.00 × 10⁸ m s⁻¹'],['Elementary charge, e','1.60 × 10⁻¹⁹ C'],['Electron mass, m_e','9.11 × 10⁻³¹ kg'],['Proton mass, m_p','1.67 × 10⁻²⁷ kg'],['Avogadro constant, N_A','6.02 × 10²³ mol⁻¹'],['Boltzmann constant, k','1.38 × 10⁻²³ J K⁻¹'],['Molar gas constant, R','8.31 J mol⁻¹ K⁻¹'],['Planck constant, h','6.63 × 10⁻³⁴ J s'],['Unified atomic mass unit, u','1.66 × 10⁻²⁷ kg (≈ 931.5 MeV/c²)']];